# Generated by Django 3.0.5 on 2020-08-28 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sanstha.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='admindetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='admin/default.jpg', max_length=255, upload_to=sanstha.models.path_rename)),
                ('phone', models.IntegerField()),
                ('adminid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
