# Generated by Django 3.0.8 on 2020-09-01 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teachermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('empid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='teacher/default.jpg', max_length=255, upload_to=members.models.path_rename)),
                ('coverphoto', models.ImageField(default='teacher/coverphoto.jpg', upload_to=members.models.path_rename)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacherdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='Hello! I am a Teacher.', max_length=500)),
                ('dob', models.DateField(null=True)),
                ('websiteurl', models.CharField(max_length=200, null=True)),
                ('fblink', models.CharField(max_length=200, null=True)),
                ('githublink', models.CharField(max_length=200, null=True)),
                ('linkedinlink', models.CharField(max_length=200, null=True)),
                ('instalink', models.CharField(max_length=200, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('stuid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='student/default.jpg', max_length=255, upload_to=members.models.path_rename_student)),
                ('coverphoto', models.ImageField(default='student/coverphoto.jpg', upload_to=members.models.path_rename_student)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='Hello! I am a student.', max_length=500)),
                ('dob', models.DateField(null=True)),
                ('websiteurl', models.CharField(max_length=200, null=True)),
                ('fblink', models.CharField(max_length=200, null=True)),
                ('githublink', models.CharField(max_length=200, null=True)),
                ('linkedinlink', models.CharField(max_length=200, null=True)),
                ('instalink', models.CharField(max_length=200, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.studentmodel')),
            ],
        ),
    ]
