# Generated by Django 3.0.8 on 2020-09-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_post_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(null=True, upload_to='post/images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='upload_post_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(null=True, upload_to='post/images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.studentmodel')),
            ],
        ),
    ]
