# Generated by Django 3.0.8 on 2020-09-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_upload_post_student_upload_post_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('designation', models.BooleanField()),
                ('desc', models.TextField()),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(null=True, upload_to='post/images')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.studentmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='upload_post_teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='upload_post_student',
        ),
        migrations.DeleteModel(
            name='upload_post_teacher',
        ),
    ]
