# Generated by Django 3.0.8 on 2020-09-04 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_auto_20200904_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('photolink', models.CharField(default='student/default.jpg', max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('designation', models.BooleanField()),
                ('desc', models.TextField()),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(null=True, upload_to='post/images')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='upload_post',
        ),
    ]
