# Generated by Django 3.0.8 on 2020-09-04 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_auto_20200904_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_pot',
            new_name='upload_post',
        ),
    ]
