# Generated by Django 3.0.8 on 2020-09-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200904_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_post',
            old_name='profile',
            new_name='profilelink',
        ),
    ]
