# Generated by Django 3.0.8 on 2020-09-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200904_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload_posts',
        ),
    ]
