# Generated by Django 3.0.8 on 2020-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_upload_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_posts',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
