# Generated by Django 3.0.8 on 2020-09-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_upload_posts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_achievements_emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=200)),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(null=True, upload_to='achievements/student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='upload_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=200)),
                ('link', models.URLField(null=True)),
                ('image', models.ImageField(null=True, upload_to='achievements/student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.studentmodel')),
            ],
        ),
    ]
