# Generated by Django 3.0.5 on 2020-09-05 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_upload_posts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_posts',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
