# Generated by Django 3.0.5 on 2020-09-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_upload_posts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_posts',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
