# Generated by Django 3.0.8 on 2020-09-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200905_1130'),
        ('members', '0011_upload_achievements_upload_achievements_emp'),
    ]

    operations = [
    ]
