# Generated by Django 3.0.7 on 2020-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_merge_20200905_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='designation',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='designation',
            field=models.BooleanField(default=1),
        ),
    ]
