# Generated by Django 3.0.8 on 2020-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_merge_20200905_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('reciever', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='latestmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=200)),
                ('myid', models.CharField(max_length=100)),
                ('fid', models.CharField(max_length=200)),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
