# Generated by Django 3.0.7 on 2020-09-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0014_auto_20200905_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('photolink', models.CharField(default='student/default.jpg', max_length=100)),
                ('profilelink', models.CharField(max_length=100)),
                ('designation', models.BooleanField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('review', models.TextField()),
                ('time', models.CharField(max_length=200, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
