# Generated by Django 3.0.5 on 2020-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_upload_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=100)),
                ('empphoto', models.CharField(max_length=100)),
                ('emplink', models.CharField(max_length=100)),
                ('empname', models.CharField(max_length=100, null=True)),
                ('review', models.TextField()),
                ('time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='upload_review',
        ),
    ]
